language: c
before_script:
  - cp makefiles/ubuntu/makefile.gcc core/Makefile
  - cd core
script:
  - make clips
after_success:
before_script: cd core
script:
  - make release
  - cd ../test_suite
  - ../core/clips -f testall.tst
