   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  06/20/16            */
   /*                                                     */
   /*                 AGENDA HEADER FILE                  */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*   Provides functionality for examining, manipulating,     */
/*   adding, and removing activations from the agenda.       */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Removed CONFLICT_RESOLUTION_STRATEGIES and     */
/*            DYNAMIC_SALIENCE compilation flags.            */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*            Added EnvGetActivationBasisPPForm function.    */
/*                                                           */
/*      6.30: Added salience groups to improve performance   */
/*            with large numbers of activations of different */
/*            saliences.                                     */
/*                                                           */
/*            Borland C (IBM_TBC) and Metrowerks CodeWarrior */
/*            (MAC_MCW, IBM_MCW) are no longer supported.    */
/*                                                           */
/*            Support for long long integers.                */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*************************************************************/

#ifndef _H_agenda

#define _H_agenda

#ifndef _H_ruledef
#include "ruledef.h"
#endif
#ifndef _H_symbol
#include "symbol.h"
#endif
#ifndef _H_match
#include "match.h"
#endif

#define WHEN_DEFINED 0
#define WHEN_ACTIVATED 1
#define EVERY_CYCLE 2

#define MAX_DEFRULE_SALIENCE  10000
#define MIN_DEFRULE_SALIENCE -10000
  
/*******************/
/* DATA STRUCTURES */
/*******************/

struct activation
  {
   struct defrule *theRule;
   struct partialMatch *basis;
   int salience;
   unsigned long long timetag;
   int randomID;
   struct activation *prev;
   struct activation *next;
  };

struct salienceGroup
  {
   int salience;
   struct activation *first;
   struct activation *last;
   struct salienceGroup *next;
   struct salienceGroup *prev;
  };

typedef struct activation ACTIVATION;

#define AGENDA_DATA 17

struct agendaData
  { 
#if DEBUGGING_FUNCTIONS
   unsigned WatchActivations;
#endif
   unsigned long NumberOfActivations;
   unsigned long long CurrentTimetag;
   int AgendaChanged;
   intBool SalienceEvaluation;
   int Strategy;
  };

#define AgendaData(theEnv) ((struct agendaData *) GetEnvironmentData(theEnv,AGENDA_DATA))

/****************************************/
/* GLOBAL EXTERNAL FUNCTION DEFINITIONS */
/****************************************/

   void                    AddActivation(void *,void *,void *);
   void                    ClearRuleFromAgenda(void *,void *);
   void                   *EnvGetNextActivation(void *,void *);
   struct partialMatch    *EnvGetActivationBasis(void *,void *);
   const char             *EnvGetActivationName(void *,void *);
   struct defrule         *EnvGetActivationRule(void *,void *);
   int                     EnvGetActivationSalience(void *,void *);
   int                     EnvSetActivationSalience(void *,void *,int);
   void                    EnvGetActivationPPForm(void *,char *,size_t,void *);
   void                    EnvGetActivationBasisPPForm(void *,char *,size_t,void *);
   intBool                 MoveActivationToTop(void *,void *);
   intBool                 EnvDeleteActivation(void *,void *);
   intBool                 DetachActivation(void *,void *);
   void                    EnvAgenda(void *,const char *,void *);
   void                    RemoveActivation(void *,void *,int,int);
   void                    RemoveAllActivations(void *);
   int                     EnvGetAgendaChanged(void *);
   void                    EnvSetAgendaChanged(void *,int);
   unsigned long           GetNumberOfActivations(void *);
   intBool                 EnvGetSalienceEvaluation(void *);
   intBool                 EnvSetSalienceEvaluation(void *,intBool);
   void                    EnvRefreshAgenda(void *,void *);
   void                    EnvReorderAgenda(void *,void *);
   void                    InitializeAgenda(void *);
   void                   *SetSalienceEvaluationCommand(void *);
   void                   *GetSalienceEvaluationCommand(void *);
   void                    RefreshAgendaCommand(void *);
   void                    RefreshCommand(void *);
   intBool                 EnvRefresh(void *,void *);
#if DEBUGGING_FUNCTIONS
   void                    AgendaCommand(void *);
#endif

#if ALLOW_ENVIRONMENT_GLOBALS

   void                    Agenda(const char *,void *);
   intBool                 DeleteActivation(void *);
   struct partialMatch    *GetActivationBasis(void *);
   const char             *GetActivationName(void *);
   void                    GetActivationPPForm(char *,unsigned,void *);
   struct defrule         *GetActivationRule(void *);
   int                     GetActivationSalience(void *);
   int                     GetAgendaChanged(void);
   void                   *GetNextActivation(void *);
   intBool                 GetSalienceEvaluation(void);
   intBool                 Refresh(void *);
   void                    RefreshAgenda(void *);
   void                    ReorderAgenda(void *);
   int                     SetActivationSalience(void *,int);
   void                    SetAgendaChanged(int);
   intBool                 SetSalienceEvaluation(int);

#endif

#endif






