   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  06/20/16            */
   /*                                                     */
   /*                                                     */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */                                      
/*      6.24: The DescribeClass macros were incorrectly      */
/*            defined. DR0862                                */
/*                                                           */
/*            Added allowed-classes slot facet.              */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Added EnvSlotDefaultP function.                */
/*                                                           */
/*            Borland C (IBM_TBC) and Metrowerks CodeWarrior */
/*            (MAC_MCW, IBM_MCW) are no longer supported.    */
/*                                                           */
/*            Used gensprintf and genstrcat instead of       */
/*            sprintf and strcat.                            */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*************************************************************/

#ifndef _H_classexm
#define _H_classexm

#if DEBUGGING_FUNCTIONS

   void                           BrowseClassesCommand(void *);
   void                           EnvBrowseClasses(void *,const char *,void *);
   void                           DescribeClassCommand(void *);
   void                           EnvDescribeClass(void *,const char *,void *);

#endif /* DEBUGGING_FUNCTIONS */

   const char                    *GetCreateAccessorString(void *);
   void                          *GetDefclassModuleCommand(void *);
   intBool                        SuperclassPCommand(void *);
   intBool                        EnvSuperclassP(void *,void *,void *);
   intBool                        SubclassPCommand(void *);
   intBool                        EnvSubclassP(void *,void *,void *);
   int                            SlotExistPCommand(void *);
   intBool                        EnvSlotExistP(void *,void *,const char *,intBool);
   int                            MessageHandlerExistPCommand(void *);
   intBool                        SlotWritablePCommand(void *);
   intBool                        EnvSlotWritableP(void *,void *,const char *);
   intBool                        SlotInitablePCommand(void *);
   intBool                        EnvSlotInitableP(void *,void *,const char *);
   intBool                        SlotPublicPCommand(void *);
   intBool                        EnvSlotPublicP(void *,void *,const char *);
   intBool                        SlotDirectAccessPCommand(void *);
   intBool                        EnvSlotDirectAccessP(void *,void *,const char *);
   void                           SlotDefaultValueCommand(void *,DATA_OBJECT_PTR);
   intBool                        EnvSlotDefaultValue(void *,void *,const char *,DATA_OBJECT_PTR);
   int                            ClassExistPCommand(void *);
   int                            EnvSlotDefaultP(void *,void *,const char *);
  
#if ALLOW_ENVIRONMENT_GLOBALS

#if DEBUGGING_FUNCTIONS
   void                           BrowseClasses(const char *,void *);
   void                           DescribeClass(const char *,void *);
#endif
   intBool                        SlotDirectAccessP(void *,const char *);
   intBool                        SlotExistP(void *,const char *,intBool);
   intBool                        SlotInitableP(void *,const char *);
   intBool                        SlotPublicP(void *,const char *);
   int                            SlotDefaultP(void *,const char *);
   intBool                        SlotWritableP(void *,const char *);
   intBool                        SubclassP(void *,void *);
   intBool                        SuperclassP(void *,void *);
   intBool                        SlotDefaultValue(void *,const char *,DATA_OBJECT_PTR);

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_classexm */
