   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  07/30/16            */
   /*                                                     */
   /*         DEFFACTS BASIC COMMANDS HEADER FILE         */
   /*******************************************************/

/*************************************************************/
/* Purpose: Implements core commands for the deffacts        */
/*   construct such as clear, reset, save, undeffacts,       */
/*   ppdeffacts, list-deffacts, and get-deffacts-list.       */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*************************************************************/

#ifndef _H_dffctbsc

#pragma once

#define _H_dffctbsc

#include "dffctdef.h"
#include "evaluatn.h"

   void                           DeffactsBasicCommands(Environment *);
   void                           UndeffactsCommand(Environment *);
   bool                           EnvUndeffacts(Environment *,Deffacts *);
   void                           GetDeffactsListFunction(Environment *,DATA_OBJECT_PTR);
   void                           EnvGetDeffactsList(Environment *,DATA_OBJECT_PTR,Defmodule *);
   void                          *DeffactsModuleFunction(Environment *);
   void                           PPDeffactsCommand(Environment *);
   bool                           PPDeffacts(Environment *,const char *,const char *);
   void                           ListDeffactsCommand(Environment *);
   void                           EnvListDeffacts(Environment *,const char *,Defmodule *);

#if ALLOW_ENVIRONMENT_GLOBALS

   void                           GetDeffactsList(DATA_OBJECT_PTR,Defmodule *);
   bool                           Undeffacts(Deffacts *);
#if DEBUGGING_FUNCTIONS
   void                           ListDeffacts(const char *,Defmodule *);
#endif

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_dffctbsc */

