   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  06/20/16            */
   /*                                                     */
   /*              FACT FUNCTIONS HEADER FILE             */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Added ppfact function.                         */
/*                                                           */
/*      6.30: Support for long long integers.                */
/*                                                           */
/*            Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*************************************************************/

#ifndef _H_factfun
#define _H_factfun

#ifndef _H_factmngr
#include "factmngr.h"
#endif

   void                           FactFunctionDefinitions(void *);
   void                          *FactRelationFunction(void *);
   void                          *FactRelation(void *);
   void                          *EnvFactDeftemplate(void *,void *);
   int                            FactExistpFunction(void *);
   int                            EnvFactExistp(void *,void *);
   void                           FactSlotValueFunction(void *,DATA_OBJECT *);
   void                           FactSlotValue(void *,void *,const char *,DATA_OBJECT *);
   void                           FactSlotNamesFunction(void *,DATA_OBJECT *);
   void                           EnvFactSlotNames(void *,void *,DATA_OBJECT *);
   void                           GetFactListFunction(void *,DATA_OBJECT *);
   void                           EnvGetFactList(void *,DATA_OBJECT *,void *);
   void                           PPFactFunction(void *);
   void                           EnvPPFact(void *,void *,const char *,int);
   struct fact                   *GetFactAddressOrIndexArgument(void *,const char *,int,int);

#if ALLOW_ENVIRONMENT_GLOBALS

   void                          *FactDeftemplate(void *);
   int                            FactExistp(void *);
   void                           FactSlotNames(void *,DATA_OBJECT *);
   void                           GetFactList(DATA_OBJECT_PTR,void *);
   void                           PPFact(void *,const char *,int);

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_factfun */

