   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  07/05/16            */
   /*                                                     */
   /*                                                     */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Changed integer type/precision.                */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*            Fixed linkage issue when DEBUGGING_FUNCTIONS   */
/*            is set to 0 and PROFILING_FUNCTIONS is set to  */
/*            1.                                             */
/*                                                           */
/*            Changed find construct functionality so that   */
/*            imported modules are search when locating a    */
/*            named construct.                               */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*************************************************************/

#ifndef _H_genrccom

#pragma once

#define _H_genrccom

#include "constrct.h"
#include "cstrccom.h"
#include "evaluatn.h"
#include "genrcfun.h"
#include "moduldef.h"
#include "symbol.h"

   void                           SetupGenericFunctions(void *);
   void                          *EnvFindDefgeneric(void *,const char *);
   void                          *EnvFindDefgenericInModule(void *,const char *);
   DEFGENERIC                    *LookupDefgenericByMdlOrScope(void *,const char *);
   DEFGENERIC                    *LookupDefgenericInScope(void *,const char *);
   void                          *EnvGetNextDefgeneric(void *,void *);
   long                           EnvGetNextDefmethod(void *,void *,long);
   bool                           EnvIsDefgenericDeletable(void *,void *);
   bool                           EnvIsDefmethodDeletable(void *,void *,long);
   void                           UndefgenericCommand(void *);
   void                          *GetDefgenericModuleCommand(void *);
   void                           UndefmethodCommand(void *);
   DEFMETHOD                     *GetDefmethodPointer(void *,long);
   bool                           EnvUndefgeneric(void *,void *);
   bool                           EnvUndefmethod(void *,void *,long);
#if ! OBJECT_SYSTEM
   void                           TypeCommand(void *,DATA_OBJECT *);
#endif
#if DEBUGGING_FUNCTIONS || PROFILING_FUNCTIONS
   void                           EnvGetDefmethodDescription(void *,char *,size_t,void *,long);
#endif
#if DEBUGGING_FUNCTIONS
   bool                           EnvGetDefgenericWatch(void *,void *);
   void                           EnvSetDefgenericWatch(void *,bool,void *);
   bool                           EnvGetDefmethodWatch(void *,void *,long);
   void                           EnvSetDefmethodWatch(void *,bool,void *,long);
   void                           PPDefgenericCommand(void *);
   void                           PPDefmethodCommand(void *);
   void                           ListDefmethodsCommand(void *);
   const char                    *EnvGetDefmethodPPForm(void *,void *,long);
   void                           ListDefgenericsCommand(void *);
   void                           EnvListDefgenerics(void *,const char *,struct defmodule *);
   void                           EnvListDefmethods(void *,const char *,void *);
#endif
   void                           GetDefgenericListFunction(void *,DATA_OBJECT *);
   void                           EnvGetDefgenericList(void *,DATA_OBJECT *,struct defmodule *);
   void                           GetDefmethodListCommand(void *,DATA_OBJECT *);
   void                           EnvGetDefmethodList(void *,void *,DATA_OBJECT *);
   void                           GetMethodRestrictionsCommand(void *,DATA_OBJECT *);
   void                           EnvGetMethodRestrictions(void *,void *,long,DATA_OBJECT *);
   SYMBOL_HN                     *GetDefgenericNamePointer(void *);
   void                           SetNextDefgeneric(void *,void *);
   const char                    *EnvDefgenericModule(void *,void *);
   const char                    *EnvGetDefgenericName(void *,void *);
   const char                    *EnvGetDefgenericPPForm(void *,void *);
   SYMBOL_HN                     *EnvGetDefgenericNamePointer(void *,void *);
   void                           EnvSetDefgenericPPForm(void *,void *,const char *);

#if ALLOW_ENVIRONMENT_GLOBALS

   void                           SetDefgenericPPForm(void *,const char *);
   const char                    *DefgenericModule(void *);
   void                          *FindDefgeneric(const char *);
   void                           GetDefgenericList(DATA_OBJECT *,struct defmodule *);
   const char                    *GetDefgenericName(void *);
   const char                    *GetDefgenericPPForm(void *);
   void                          *GetNextDefgeneric(void *);
   bool                           IsDefgenericDeletable(void *);
   bool                           Undefgeneric(void *);
   void                           GetDefmethodList(void *,DATA_OBJECT_PTR);
   void                           GetMethodRestrictions(void *,long,DATA_OBJECT *);
   long                           GetNextDefmethod(void *,long );
   bool                           IsDefmethodDeletable(void *,long );
   bool                           Undefmethod(void *,long );
#if DEBUGGING_FUNCTIONS
   bool                           GetDefgenericWatch(void *);
   void                           ListDefgenerics(const char *,struct defmodule *);
   void                           SetDefgenericWatch(bool,void *);
   const char                    *GetDefmethodPPForm(void *,long);
   bool                           GetDefmethodWatch(void *,long);
   void                           ListDefmethods(const char *,void *);
   void                           SetDefmethodWatch(bool,void *,long);
#endif /* DEBUGGING_FUNCTIONS */
#if DEBUGGING_FUNCTIONS || PROFILING_FUNCTIONS
   void                           GetDefmethodDescription(char *,int,void *,long );
#endif /* DEBUGGING_FUNCTIONS || PROFILING_FUNCTIONS */

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_genrccom */





