   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  07/30/16            */
   /*                                                     */
   /*                                                     */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Changed integer type/precision.                */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*            Fixed linkage issue when DEBUGGING_FUNCTIONS   */
/*            is set to 0 and PROFILING_FUNCTIONS is set to  */
/*            1.                                             */
/*                                                           */
/*            Changed find construct functionality so that   */
/*            imported modules are search when locating a    */
/*            named construct.                               */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*************************************************************/

#ifndef _H_genrccom

#pragma once

#define _H_genrccom

#include "constrct.h"
#include "cstrccom.h"
#include "evaluatn.h"
#include "genrcfun.h"
#include "moduldef.h"
#include "symbol.h"

   void                           SetupGenericFunctions(Environment *);
   Defgeneric                    *EnvFindDefgeneric(Environment *,const char *);
   Defgeneric                    *EnvFindDefgenericInModule(Environment *,const char *);
   Defgeneric                    *LookupDefgenericByMdlOrScope(Environment *,const char *);
   Defgeneric                    *LookupDefgenericInScope(Environment *,const char *);
   Defgeneric                    *EnvGetNextDefgeneric(Environment *,Defgeneric *);
   long                           EnvGetNextDefmethod(Environment *,Defgeneric *,long);
   bool                           EnvIsDefgenericDeletable(Environment *,Defgeneric *);
   bool                           EnvIsDefmethodDeletable(Environment *,Defgeneric *,long);
   void                           UndefgenericCommand(Environment *);
   void                          *GetDefgenericModuleCommand(Environment *);
   void                           UndefmethodCommand(Environment *);
   Defmethod                     *GetDefmethodPointer(Defgeneric *,long);
   bool                           EnvUndefgeneric(Environment *,Defgeneric *);
   bool                           EnvUndefmethod(Environment *,Defgeneric *,long);
#if ! OBJECT_SYSTEM
   void                           TypeCommand(void *,DATA_OBJECT *);
#endif
#if DEBUGGING_FUNCTIONS || PROFILING_FUNCTIONS
   void                           EnvGetDefmethodDescription(Environment *,char *,size_t,Defgeneric *,long);
#endif
#if DEBUGGING_FUNCTIONS
   bool                           EnvGetDefgenericWatch(Environment *,Defgeneric *);
   void                           EnvSetDefgenericWatch(Environment *,bool,Defgeneric *);
   bool                           EnvGetDefmethodWatch(Environment *,Defgeneric *,long);
   void                           EnvSetDefmethodWatch(Environment *,bool,Defgeneric *,long);
   void                           PPDefgenericCommand(Environment *);
   void                           PPDefmethodCommand(Environment *);
   void                           ListDefmethodsCommand(Environment *);
   const char                    *EnvGetDefmethodPPForm(Environment *,Defgeneric *,long);
   void                           ListDefgenericsCommand(Environment *);
   void                           EnvListDefgenerics(Environment *,const char *,Defmodule *);
   void                           EnvListDefmethods(Environment *,const char *,Defgeneric *);
#endif
   void                           GetDefgenericListFunction(Environment *,DATA_OBJECT *);
   void                           EnvGetDefgenericList(Environment *,DATA_OBJECT *,Defmodule *);
   void                           GetDefmethodListCommand(Environment *,DATA_OBJECT *);
   void                           EnvGetDefmethodList(Environment *,Defgeneric *,DATA_OBJECT *);
   void                           GetMethodRestrictionsCommand(Environment *,DATA_OBJECT *);
   void                           EnvGetMethodRestrictions(Environment *,Defgeneric *,long,DATA_OBJECT *);
   SYMBOL_HN                     *GetDefgenericNamePointer(Defgeneric *);
   void                           SetNextDefgeneric(Defgeneric *,Defgeneric *);
   const char                    *EnvDefgenericModule(Environment *,Defgeneric *);
   const char                    *EnvGetDefgenericName(Environment *,Defgeneric *);
   const char                    *EnvGetDefgenericPPForm(Environment *,Defgeneric *);
   SYMBOL_HN                     *EnvGetDefgenericNamePointer(Environment *,Defgeneric *);
   void                           EnvSetDefgenericPPForm(Environment *,Defgeneric *,const char *);

#if ALLOW_ENVIRONMENT_GLOBALS

   void                           SetDefgenericPPForm(Defgeneric *,const char *);
   const char                    *DefgenericModule(Defgeneric *);
   Defgeneric                    *FindDefgeneric(const char *);
   void                           GetDefgenericList(DATA_OBJECT *,Defmodule *);
   const char                    *GetDefgenericName(Defgeneric *);
   const char                    *GetDefgenericPPForm(Defgeneric *);
   Defgeneric                    *GetNextDefgeneric(Defgeneric *);
   bool                           IsDefgenericDeletable(Defgeneric *);
   bool                           Undefgeneric(Defgeneric *);
   void                           GetDefmethodList(Defgeneric *,DATA_OBJECT_PTR);
   void                           GetMethodRestrictions(Defgeneric *,long,DATA_OBJECT *);
   long                           GetNextDefmethod(Defgeneric *,long );
   bool                           IsDefmethodDeletable(Defgeneric *,long );
   bool                           Undefmethod(Defgeneric *,long );
#if DEBUGGING_FUNCTIONS
   bool                           GetDefgenericWatch(Defgeneric *);
   void                           ListDefgenerics(const char *,Defmodule *);
   void                           SetDefgenericWatch(bool,Defgeneric *);
   const char                    *GetDefmethodPPForm(Defgeneric *,long);
   bool                           GetDefmethodWatch(Defgeneric *,long);
   void                           ListDefmethods(const char *,Defgeneric *);
   void                           SetDefmethodWatch(bool,Defgeneric *,long);
#endif /* DEBUGGING_FUNCTIONS */
#if DEBUGGING_FUNCTIONS || PROFILING_FUNCTIONS
   void                           GetDefmethodDescription(char *,int,Defgeneric *,long );
#endif /* DEBUGGING_FUNCTIONS || PROFILING_FUNCTIONS */

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_genrccom */





