   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  06/20/16            */
   /*                                                     */
   /*                                                     */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Loading a binary instance file from a run-time */
/*            program caused a bus error. DR0866             */
/*                                                           */
/*            Removed LOGICAL_DEPENDENCIES compilation flag. */
/*                                                           */
/*            Converted INSTANCE_PATTERN_MATCHING to         */
/*            DEFRULE_CONSTRUCT.                             */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Changed integer type/precision.                */
/*                                                           */
/*            Changed garbage collection algorithm.          */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*************************************************************/

#ifndef _H_inscom
#define _H_inscom

#ifndef _H_object
#include "object.h"
#endif

#ifndef _H_insfun
#include "insfun.h"
#endif

#define INSTANCE_DATA 29

struct instanceData
  { 
   INSTANCE_TYPE DummyInstance;
   INSTANCE_TYPE **InstanceTable;
   int MaintainGarbageInstances;
   int MkInsMsgPass;
   int ChangesToInstances;
   IGARBAGE *InstanceGarbageList;
   struct patternEntityRecord InstanceInfo;
   INSTANCE_TYPE *InstanceList;  
   unsigned long GlobalNumberOfInstances;
   INSTANCE_TYPE *CurrentInstance;
   INSTANCE_TYPE *InstanceListBottom;
   intBool ObjectModDupMsgValid;
  };

#define InstanceData(theEnv) ((struct instanceData *) GetEnvironmentData(theEnv,INSTANCE_DATA))

   void                           SetupInstances(void *);
   intBool                        EnvDeleteInstance(void *,void *);
   intBool                        EnvUnmakeInstance(void *,void *);
#if DEBUGGING_FUNCTIONS
   void                           InstancesCommand(void *);
   void                           PPInstanceCommand(void *);
   void                           EnvInstances(void *,const char *,void *,const char *,int);
#endif
   void                          *EnvMakeInstance(void *,const char *);
   void                          *EnvCreateRawInstance(void *,void *,const char *);
   void                          *EnvFindInstance(void *,void *,const char *,unsigned);
   int                            EnvValidInstanceAddress(void *,void *);
   void                           EnvDirectGetSlot(void *,void *,const char *,DATA_OBJECT *);
   int                            EnvDirectPutSlot(void *,void *,const char *,DATA_OBJECT *);
   const char                    *EnvGetInstanceName(void *,void *);
   void                          *EnvGetInstanceClass(void *,void *);
   unsigned long GetGlobalNumberOfInstances(void *);
   void                          *EnvGetNextInstance(void *,void *);
   void                          *GetNextInstanceInScope(void *,void *);
   void                          *EnvGetNextInstanceInClass(void *,void *,void *);
   void                          *EnvGetNextInstanceInClassAndSubclasses(void *,void **,void *,DATA_OBJECT *);
   void                           EnvGetInstancePPForm(void *,char *,size_t,void *);
   void                           ClassCommand(void *,DATA_OBJECT *);
   intBool                        DeleteInstanceCommand(void *);
   intBool                        UnmakeInstanceCommand(void *);
   void                           SymbolToInstanceName(void *,DATA_OBJECT *);
   void                          *InstanceNameToSymbol(void *);
   void                           InstanceAddressCommand(void *,DATA_OBJECT *);
   void                           InstanceNameCommand(void *,DATA_OBJECT *);
   intBool                        InstanceAddressPCommand(void *);
   intBool                        InstanceNamePCommand(void *);
   intBool                        InstancePCommand(void *);
   intBool                        InstanceExistPCommand(void *);
   intBool                        CreateInstanceHandler(void *);

#if ALLOW_ENVIRONMENT_GLOBALS

   const char                    *GetInstanceName(void *);
   void                          *CreateRawInstance(void *,const char *);
   intBool                        DeleteInstance(void *);
   void                           DirectGetSlot(void *,const char *,DATA_OBJECT *);
   int                            DirectPutSlot(void *,const char *,DATA_OBJECT *);
   void                          *FindInstance(void *,const char *,unsigned);
   void                          *GetInstanceClass(void *);
   void                           GetInstancePPForm(char *,unsigned,void *);
   void                          *GetNextInstance(void *);
   void                          *GetNextInstanceInClass(void *,void *);
   void                          *GetNextInstanceInClassAndSubclasses(void **,void *,DATA_OBJECT *);
   void                           Instances(const char *,void *,const char *,int);
#if DEBUGGING_FUNCTIONS
   void                          *MakeInstance(const char *);
#endif
   intBool                        UnmakeInstance(void *);
   int                            ValidInstanceAddress(void *);

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_inscom */





