   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  08/25/16            */
   /*                                                     */
   /*                                                     */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Changed integer type/precision.                */
/*                                                           */
/*            Changed garbage collection algorithm.          */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*            UDF redesign.                                  */
/*                                                           */
/*************************************************************/

#ifndef _H_insquery

#pragma once

#define _H_insquery

#if INSTANCE_SET_QUERIES

#include "object.h"

typedef struct query_class
  {
   Defclass *cls;
   Defmodule *theModule;
   struct query_class *chain,*nxt;
  } QUERY_CLASS;

typedef struct query_soln
  {
   Instance **soln;
   struct query_soln *nxt;
  } QUERY_SOLN;

typedef struct query_core
  {
   Instance **solns;
   EXPRESSION *query,*action;
   QUERY_SOLN *soln_set,*soln_bottom;
   unsigned soln_size,soln_cnt;
   CLIPSValue *result;
  } QUERY_CORE;

typedef struct query_stack
  {
   QUERY_CORE *core;
   struct query_stack *nxt;
  } QUERY_STACK;

#define INSTANCE_QUERY_DATA 31

struct instanceQueryData
  { 
   SYMBOL_HN *QUERY_DELIMETER_SYMBOL;
   QUERY_CORE *QueryCore;
   QUERY_STACK *QueryCoreStack;
   bool AbortQuery;
  };

#define InstanceQueryData(theEnv) ((struct instanceQueryData *) GetEnvironmentData(theEnv,INSTANCE_QUERY_DATA))

#define QUERY_DELIMETER_STRING     "(QDS)"

   void                           SetupQuery(Environment *);
   void                           GetQueryInstance(Environment *,UDFContext *,CLIPSValue *);
   void                           GetQueryInstanceSlot(Environment *,UDFContext *,CLIPSValue *);
   void                           AnyInstances(Environment *,UDFContext *,CLIPSValue *);
   void                           QueryFindInstance(Environment *,UDFContext *,CLIPSValue *);
   void                           QueryFindAllInstances(Environment *,UDFContext *,CLIPSValue *);
   void                           QueryDoForInstance(Environment *,UDFContext *,CLIPSValue *);
   void                           QueryDoForAllInstances(Environment *,UDFContext *,CLIPSValue *);
   void                           DelayedQueryDoForAllInstances(Environment *,UDFContext *,CLIPSValue *);

#endif /* INSTANCE_SET_QUERIES */

#endif /* _H_insquery */





