   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  07/30/16            */
   /*                                                     */
   /*          MISCELLANEOUS FUNCTIONS HEADER FILE        */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*            Changed name of variable exp to theExp         */
/*            because of Unix compiler warnings of shadowed  */
/*            definitions.                                   */
/*                                                           */
/*      6.24: Removed CONFLICT_RESOLUTION_STRATEGIES,        */
/*            DYNAMIC_SALIENCE, INCREMENTAL_RESET,           */
/*            LOGICAL_DEPENDENCIES, IMPERATIVE_METHODS       */
/*            INSTANCE_PATTERN_MATCHING,                     */
/*            IMPERATIVE_MESSAGE_HANDLERS, and               */
/*            AUXILIARY_MESSAGE_HANDLERS compilation flags.  */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Support for long long integers.                */
/*                                                           */
/*            Used gensprintf instead of sprintf.            */
/*                                                           */
/*            Removed conditional code for unsupported       */
/*            compilers/operating systems.                   */
/*                                                           */
/*            Renamed EX_MATH compiler flag to               */
/*            EXTENDED_MATH_FUNCTIONS.                       */
/*                                                           */
/*            Combined BASIC_IO and EXT_IO compilation       */
/*            flags into the IO_FUNCTIONS compilation flag.  */
/*                                                           */    
/*            Removed code associated with HELP_FUNCTIONS    */
/*            and EMACS_EDITOR compiler flags.               */
/*                                                           */    
/*            Added operating-system function.               */
/*                                                           */ 
/*            Added new function (for future use).           */
/*                                                           */ 
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*      6.31: Added local-time and gm-time functions.        */
/*                                                           */
/*      6.40: Refactored code to reduce header dependencies  */
/*            in sysdep.c.                                   */
/*                                                           */
/*            Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*************************************************************/

#ifndef _H_miscfun

#pragma once

#define _H_miscfun

   void                           MiscFunctionDefinitions(Environment *);
   void                           CreateFunction(Environment *,DATA_OBJECT_PTR);
   long long                      SetgenFunction(Environment *);
   void                          *GensymFunction(Environment *);
   void                          *GensymStarFunction(Environment *);
   long long                      RandomFunction(Environment *);
   void                           SeedFunction(Environment *);
   long long                      LengthFunction(Environment *);
   void                           ConserveMemCommand(Environment *);
   long long                      ReleaseMemCommand(Environment *);
   long long                      MemUsedCommand(Environment *);
   long long                      MemRequestsCommand(Environment *);
   void                           OptionsCommand(Environment *);
   void                          *OperatingSystemFunction(Environment *);
   void                           ExpandFuncCall(Environment *,DATA_OBJECT *);
   void                           DummyExpandFuncMultifield(Environment *,DATA_OBJECT *);
   void                          *CauseEvaluationError(Environment *);
   bool                           SetSequenceOperatorRecognitionCommand(Environment *);
   bool                           GetSequenceOperatorRecognitionCommand(Environment *);
   void                          *GetFunctionRestrictions(Environment *);
   void                           AproposCommand(Environment *);
   void                          *GensymStar(Environment *);
   void                           GetFunctionListFunction(Environment *,DATA_OBJECT *);
   void                           FuncallFunction(Environment *,DATA_OBJECT *);
   void                           NewFunction(Environment *,DATA_OBJECT *);
   void                           CallFunction(Environment *,DATA_OBJECT *);
   double                         TimerFunction(Environment *);
   double                         TimeFunction(Environment *);
   void                           SystemCommand(Environment *);
   void                           LocalTimeFunction(Environment *,DATA_OBJECT *);
   void                           GMTimeFunction(Environment *,DATA_OBJECT *);

#endif /* _H_miscfun */






