   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  06/20/16            */
   /*                                                     */
   /*         DEFRULE BASIC COMMANDS HEADER FILE          */
   /*******************************************************/

/*************************************************************/
/* Purpose: Implements core commands for the defrule         */
/*   construct such as clear, reset, save, undefrule,        */
/*   ppdefrule, list-defrules, and                           */
/*   get-defrule-list.                                       */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*            Changed name of variable log to logName        */
/*            because of Unix compiler warnings of shadowed  */
/*            definitions.                                   */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Support for join network changes.              */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*            Added code to prevent a clear command from     */
/*            being executed during fact assertions via      */
/*            JoinOperationInProgress mechanism.             */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*************************************************************/

#ifndef _H_rulebsc

#pragma once

#define _H_rulebsc

#include "evaluatn.h"

   void                           DefruleBasicCommands(void *);
   void                           UndefruleCommand(void *);
   intBool                        EnvUndefrule(void *,void *);
   void                           GetDefruleListFunction(void *,DATA_OBJECT_PTR);
   void                           EnvGetDefruleList(void *,DATA_OBJECT_PTR,void *);
   void                          *DefruleModuleFunction(void *);
#if DEBUGGING_FUNCTIONS
   void                           PPDefruleCommand(void *);
   int                            PPDefrule(void *,const char *,const char *);
   void                           ListDefrulesCommand(void *);
   void                           EnvListDefrules(void *,const char *,void *);
   unsigned                       EnvGetDefruleWatchFirings(void *,void *);
   unsigned                       EnvGetDefruleWatchActivations(void *,void *);
   void                           EnvSetDefruleWatchFirings(void *,unsigned,void *);
   void                           EnvSetDefruleWatchActivations(void *,unsigned,void *);
   unsigned                       DefruleWatchAccess(void *,int,unsigned,struct expr *);
   unsigned                       DefruleWatchPrint(void *,const char *,int,struct expr *);
#endif

#if ALLOW_ENVIRONMENT_GLOBALS

   void                           GetDefruleList(DATA_OBJECT_PTR,void *);
#if DEBUGGING_FUNCTIONS
   unsigned                       GetDefruleWatchActivations(void *);
   unsigned                       GetDefruleWatchFirings(void *);
   void                           ListDefrules(const char *,void *);
   void                           SetDefruleWatchActivations(unsigned,void *);
   void                           SetDefruleWatchFirings(unsigned,void *);
#endif
   intBool                        Undefrule(void *);

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_rulebsc */


