   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  07/05/16            */
   /*                                                     */
   /*         DEFRULE BASIC COMMANDS HEADER FILE          */
   /*******************************************************/

/*************************************************************/
/* Purpose: Implements core commands for the defrule         */
/*   construct such as clear, reset, save, undefrule,        */
/*   ppdefrule, list-defrules, and                           */
/*   get-defrule-list.                                       */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*            Changed name of variable log to logName        */
/*            because of Unix compiler warnings of shadowed  */
/*            definitions.                                   */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Support for join network changes.              */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*            Added code to prevent a clear command from     */
/*            being executed during fact assertions via      */
/*            JoinOperationInProgress mechanism.             */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*************************************************************/

#ifndef _H_rulebsc

#pragma once

#define _H_rulebsc

#include "evaluatn.h"

   void                           DefruleBasicCommands(void *);
   void                           UndefruleCommand(void *);
   bool                           EnvUndefrule(void *,void *);
   void                           GetDefruleListFunction(void *,DATA_OBJECT_PTR);
   void                           EnvGetDefruleList(void *,DATA_OBJECT_PTR,void *);
   void                          *DefruleModuleFunction(void *);
#if DEBUGGING_FUNCTIONS
   void                           PPDefruleCommand(void *);
   int                            PPDefrule(void *,const char *,const char *);
   void                           ListDefrulesCommand(void *);
   void                           EnvListDefrules(void *,const char *,void *);
   bool                           EnvGetDefruleWatchFirings(void *,void *);
   bool                           EnvGetDefruleWatchActivations(void *,void *);
   void                           EnvSetDefruleWatchFirings(void *,bool,void *);
   void                           EnvSetDefruleWatchActivations(void *,bool,void *);
   bool                           DefruleWatchAccess(void *,int,bool,struct expr *);
   bool                           DefruleWatchPrint(void *,const char *,int,struct expr *);
#endif

#if ALLOW_ENVIRONMENT_GLOBALS

   void                           GetDefruleList(DATA_OBJECT_PTR,void *);
#if DEBUGGING_FUNCTIONS
   bool                           GetDefruleWatchActivations(void *);
   bool                           GetDefruleWatchFirings(void *);
   void                           ListDefrules(const char *,void *);
   void                           SetDefruleWatchActivations(bool,void *);
   void                           SetDefruleWatchFirings(bool,void *);
#endif
   bool                           Undefrule(void *);

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_rulebsc */


