   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  06/20/16            */
   /*                                                     */
   /*       DEFTEMPLATE BASIC COMMANDS HEADER FILE        */
   /*******************************************************/

/*************************************************************/
/* Purpose: Implements core commands for the deftemplate     */
/*   construct such as clear, reset, save, undeftemplate,    */
/*   ppdeftemplate, list-deftemplates, and                   */
/*   get-deftemplate-list.                                   */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*      Brian L. Dantes                                      */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*            Changed name of variable log to logName        */
/*            because of Unix compiler warnings of shadowed  */
/*            definitions.                                   */
/*                                                           */
/*      6.24: Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*            Corrected code to remove compiler warnings     */
/*            when ENVIRONMENT_API_ONLY flag is set.         */
/*                                                           */
/*      6.30: Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*************************************************************/

#ifndef _H_tmpltbsc

#pragma once

#define _H_tmpltbsc

#include "evaluatn.h"

   void                           DeftemplateBasicCommands(void *);
   void                           UndeftemplateCommand(void *);
   intBool                        EnvUndeftemplate(void *,void *);
   void                           GetDeftemplateListFunction(void *,DATA_OBJECT_PTR);
   void                           EnvGetDeftemplateList(void *,DATA_OBJECT_PTR,void *);
   void                          *DeftemplateModuleFunction(void *);
#if DEBUGGING_FUNCTIONS
   void                           PPDeftemplateCommand(void *);
   int                            PPDeftemplate(void *,const char *,const char *);
   void                           ListDeftemplatesCommand(void *);
   void                           EnvListDeftemplates(void *,const char *,void *);
   unsigned                       EnvGetDeftemplateWatch(void *,void *);
   void                           EnvSetDeftemplateWatch(void *,unsigned,void *);
   unsigned                       DeftemplateWatchAccess(void *,int,unsigned,struct expr *);
   unsigned                       DeftemplateWatchPrint(void *,const char *,int,struct expr *);
#endif

#if ALLOW_ENVIRONMENT_GLOBALS

   void                           GetDeftemplateList(DATA_OBJECT_PTR,void *);
#if DEBUGGING_FUNCTIONS
   unsigned                       GetDeftemplateWatch(void *);
   void                           ListDeftemplates(const char *,void *);
   void                           SetDeftemplateWatch(unsigned,void *);
#endif
   intBool                        Undeftemplate(void *);

#endif /* ALLOW_ENVIRONMENT_GLOBALS */

#endif /* _H_tmpltbsc */


