(clear)
(regex-match)
(regex-match foo 1)
(regex-match foo "1")
(regex-match foo bar)
(regex-match foo foobar)
(regex-match foo "foobar")
(regex-match "foo" foobar)
(regex-match "foo" "foobar")
(regex-match "" foobar)
(regex-match foo FOOBAR)
(regex-match ☃ "Foo☃Bar")
(regex-match "(www.)(.*)(.com|.net)" "http://www.clipsrules.net")
(regex-imatch)
(regex-imatch foo 1)
(regex-imatch foo "1")
(regex-imatch foo bar)
(regex-imatch foo foobar)
(regex-imatch foo "foobar")
(regex-imatch "foo" foobar)
(regex-imatch "foo" "foobar")
(regex-imatch "" foobar)
(regex-imatch foo FOOBAR)
(regex-imatch ☃ "Foo☃Bar")
(regex-imatch "(www.)(.*)(.com|.net)" "http://www.clipsrules.net")
