(unwatch all)
(clear)
(dribble-on "Actual//tmplv640.out")
(batch "tmplv640.bat")
(dribble-off)
(clear)
(open "Results//tmplv640.rsl" tmplv640 "w")
(load "compline.clp")
(printout tmplv640 "tmplv640.bat differences are as follows:" crlf)
(compare-files "Expected//tmplv640.out" "Actual//tmplv640.out" tmplv640)
(close tmplv640)
